# Development Dockerfile for gateway-service
FROM node:20-alpine

# Install pnpm globally
RUN npm install -g pnpm

# Set the working directory to the root of the monorepo
WORKDIR /app

# Dependency Installation 

COPY pnpm-workspace.yaml package.json tsconfig.base.json pnpm-lock.yaml ./
COPY services/gateway-service/package.json ./services/gateway-service/
COPY shared/package.json ./shared/

ENV NODE_ENV=development

RUN pnpm install --ignore-scripts

COPY services/gateway-service ./services/gateway-service/
COPY shared ./shared/


EXPOSE 3000

CMD ["pnpm", "--filter", "api-gateway-service", "start:dev"]