// Common error codes for the notification system
export const BAD_REQUEST = "BAD_REQUEST"
export const UNAUTHORIZED = "UNAUTHORIZED"
export const FORBIDDEN = "FORBIDDEN"
export const NOT_FOUND = "NOT_FOUND"
export const CONFLICT = "CONFLICT"
export const INTERNAL_SERVER_ERROR = "INTERNAL_SERVER_ERROR"
export const SERVICE_UNAVAILABLE = "SERVICE_UNAVAILABLE"

// Authentication & Authorization
export const INVALID_CREDENTIALS = "INVALID_CREDENTIALS"
export const TOKEN_EXPIRED = "TOKEN_EXPIRED"
export const TOKEN_INVALID = "TOKEN_INVALID"
export const INSUFFICIENT_PERMISSIONS = "INSUFFICIENT_PERMISSIONS"

// User related
export const USER_NOT_FOUND = "USER_NOT_FOUND"
export const USER_ALREADY_EXISTS = "USER_ALREADY_EXISTS"
export const INVALID_USER_DATA = "INVALID_USER_DATA"

// Template related
export const TEMPLATE_NOT_FOUND = "TEMPLATE_NOT_FOUND"
export const INVALID_TEMPLATE = "INVALID_TEMPLATE"

// Notification related
export const NOTIFICATION_NOT_FOUND = "NOTIFICATION_NOT_FOUND"
export const NOTIFICATION_SEND_FAILED = "NOTIFICATION_SEND_FAILED"
export const INVALID_NOTIFICATION_TYPE = "INVALID_NOTIFICATION_TYPE"

// Validation
export const VALIDATION_ERROR = "VALIDATION_ERROR"
export const INVALID_INPUT = "INVALID_INPUT"
export const MISSING_REQUIRED_FIELD = "MISSING_REQUIRED_FIELD"

// Service related
export const SERVICE_DISCOVERY_FAILED = "SERVICE_DISCOVERY_FAILED"
export const EXTERNAL_SERVICE_ERROR = "EXTERNAL_SERVICE_ERROR"
export const DATABASE_ERROR = "DATABASE_ERROR"
export const QUEUE_ERROR = "QUEUE_ERROR"
